#!/bin/bash
# Orient Spindle to 0 degrees
halcmd setp motion.spindle-orient-angle 0
halcmd setp motion.spindle-orient 1
# Wait for spindle to settle (max 3 seconds)
for i in {1..30}; do
    if [ "$(halcmd getp motion.spindle-is-oriented)" == "TRUE" ]; then break; fi
    sleep 0.1
done
# Turn on Blum Probe
halcmd setp motion.digital-out-00 1
sleep 0.5
exit 0
